In [1]:
import os

os.chdir('C:/대학원/2019-1/1.전공/2.데이터마이닝/project/도로/result')
os.getcwd()

'C:\\대학원\\2019-1\\1.전공\\2.데이터마이닝\\project\\도로\\result'

In [2]:
import pandas as pd

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
pd.set_option('display.max_columns', 500)
train.head(2)

,date,days,road_name,link_id,start_point,end_point,direction,road_length,road_num,road_type,urban_suburb,district,holiday,special,vacation,time,inter_num,d1,d2,d3,d4,victims,severity,accident_count,temperature,wind,rain,snow,cctv,kids,speed_limit,entrance,signal,SO2,CO,O3,NO2,PM10,PM2.5,month,weekend,y
0,20181112,월,언주로,1220024700,개나리아파트,르네상스호텔,하행,484,4.0,주간선도로,외곽,강남구,0,0,0,22,14.0,1,63,307,34,405,1156,246,10.5,1.1,0.0,0.0,1.0,0.0,60.0,76.0,68.0,0.007,0.6,0.002,0.055,36.0,20.0,11,0,28.16
1,20180721,토,양재대로,1220000200,구룡사앞,구룡터널,상행,851,4.0,주간선도로,외곽,강남구,0,0,0,21,28.0,3,132,434,52,621,1786,419,31.8,1.9,0.0,0.0,0.0,0.0,50.0,64.0,115.0,0.006,0.3,0.020,0.027,29.0,21.0,7,1,36.57

In [5]:
train.columns

Index(['date', 'days', 'road_name', 'link_id', 'start_point', 'end_point',
       'direction', 'road_length', 'road_num', 'road_type', 'urban_suburb',
       'district', 'holiday', 'special', 'vacation', 'time', 'inter_num', 'd1',
       'd2', 'd3', 'd4', 'victims', 'severity', 'accident_count',
       'temperature', 'wind', 'rain', 'snow', 'cctv', 'kids', 'speed_limit',
       'entrance', 'signal', 'SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM2.5',
       'month', 'weekend', 'y'],
      dtype='object')

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1042732 entries, 0 to 1042731
Data columns (total 42 columns):
date              1042732 non-null int64
days              1042732 non-null object
road_name         1042732 non-null object
link_id           1042732 non-null int64
start_point       1042732 non-null object
end_point         1042732 non-null object
direction         1042732 non-null object
road_length       1042732 non-null int64
road_num          1042732 non-null float64
road_type         1042732 non-null object
urban_suburb      1042732 non-null object
district          1042732 non-null object
holiday           1042732 non-null int64
special           1042732 non-null int64
vacation          1042732 non-null int64
time              1042732 non-null int64
inter_num         1042732 non-null float64
d1                1042732 non-null int64
d2                1042732 non-null int64
d3                1042732 non-null int64
d4                1042732 non-null int64
victims           1042732 non-null int64
severity          1042732 non-null int64
accident_count    1042732 non-null int64
temperature       1042732 non-null float64
wind              1042732 non-null float64
rain              1042732 non-null float64
snow              1042732 non-null float64
cctv              1042732 non-null float64
kids              1042732 non-null float64
speed_limit       1042732 non-null float64
entrance          1042732 non-null float64
signal            1042732 non-null float64
SO2               1042732 non-null float64
CO                1042732 non-null float64
O3                1042732 non-null float64
NO2               1042732 non-null float64
PM10              1042732 non-null float64
PM2.5             1042732 non-null float64
month             1042732 non-null int64
weekend           1042732 non-null int64
y                 1042732 non-null float64
dtypes: float64(18), int64(16), object(8)
memory usage: 334.1+ MB