In [2]:
import os

os.chdir('C:/대학원/2019-1/1.전공/2.데이터마이닝/project/도로/result')
os.getcwd()

'C:\\대학원\\2019-1\\1.전공\\2.데이터마이닝\\project\\도로\\result'

In [3]:
import pandas as pd
car = pd.read_csv("car_ej.csv")

In [4]:
cluster = pd.read_csv("cluster_df.csv")

In [5]:
car.head(2)

,date,days,road_name,link_id,start_point,end_point,direction,road_length,road_num,road_type,...,special,vacation,inter_num,d1,d2,d3,d4,victims,severity,accident_count
0,20180201,목,강남대로,1220021100,우성아파트,강남역,상행,586,5.0,주간선도로,...,0,0,15.0,3,69,338,28,438,1285,280
1,20180201,목,강남대로,1220016200,우성아파트,뱅뱅사거리,하행,414,5.0,주간선도로,...,0,0,15.0,3,69,338,28,438,1285,280

In [6]:
cluster.head(2)

      link_id  cluster
0  1220024700        2
1  1220000200        0

In [7]:
car = pd.merge(car, cluster, how = 'left', left_on = ['link_id'], right_on = ['link_id'])
car.head()

,date,days,road_name,link_id,start_point,end_point,direction,road_length,road_num,road_type,...,vacation,inter_num,d1,d2,d3,d4,victims,severity,accident_count,cluster
0,20180201,목,강남대로,1220021100,우성아파트,강남역,상행,586,5.0,주간선도로,...,0,15.0,3,69,338,28,438,1285,280,2
1,20180201,목,강남대로,1220016200,우성아파트,뱅뱅사거리,하행,414,5.0,주간선도로,...,0,15.0,3,69,338,28,438,1285,280,2
2,20180201,목,개포로,1220020500,대청초교,대청역,상행,862,2.0,기타도로,...,0,8.0,0,21,31,5,57,161,39,0
3,20180201,목,개포로,1220018600,대청역,수서경찰서,상행,318,2.0,기타도로,...,0,8.0,0,21,31,5,57,161,39,2
4,20180201,목,개포로,1220017200,수서경찰서,대모산입구역,상행,333,2.0,기타도로,...,0,8.0,0,21,31,5,57,161,39,2

In [9]:
car.to_csv("car_cluster.csv",index=False)

In [11]:
len(car.link_id.unique())

295

In [15]:
col = ['start_point','end_point']
car[car.cluster==0][col]

        start_point      end_point
2              대청초교            대청역
7              개포동역           개포고교
9              구룡초교          포이사거리
11             개포고교           개포동역
16              대청역           대청초교
17             일원터널            일원역
19              수서역            광평교
21              일원역           일원터널
24              도곡역            대치역
25              대치역           학여울역
26             학여울역         탄천1교서측
28      남부순환로탄천IC합류    남부순환로탄천IC진입
29      남부순환로탄천IC진입           수서IC
30             수서IC    남부순환로탄천IC진입
31      남부순환로탄천IC진입    남부순환로탄천IC합류
33           탄천1교서측           학여울역
34             학여울역            대치역
35              대치역            도곡역
39           동호대교남단           압구정역
40             압구정역         강남을지병원
41           강남을지병원            학동역
42              학동역            차병원
43              차병원            역삼역
46         도곡1동주민센터          양재전화국
52              역삼역            차병원
53              차병원            학동역
54              학동역         강남을지병원
55           강남을지병원           압구정역
56             압구정역         동호대교남단
57           동호대교남단         동호대교북단
...             ...            ...
741794        경복아파트           서울세관
741795         서울세관           도산공원
741796         도산공원      성수대교남단교차로
741798       성수대교남단         성수대교북단
741803         도성초교          대치사거리
741804        대치사거리           휘문고교
741807         휘문고교          대치사거리
741808        대치사거리           도성초교
741815        경기고교앞            코엑스
741816          코엑스            삼성역
741831          삼성역            코엑스
741832          코엑스          경기고교앞
741835       영동대교남단         영동대교북단
741836  올림픽대로동부간선JC         영동대교남단
741838       성수대교남단         동호대교남단
741839       동호대교남단         한남대교남단
741840       동호대교남단         성수대교남단
741842       영동대교남단    올림픽대로동부간선JC
741846       삼성서울병원            일원역
741847          일원역         삼성서울병원
741852          삼성역         포스코사거리
741853       포스코사거리            선릉역
741861          선릉역         포스코사거리
741862       포스코사거리            삼성역
741871        경기고교앞          청담공원앞
741872        청담공원앞          강남구청역
741875          학동역            논현역
741878        강남구청역          청담공원앞
741879        청담공원앞          경기고교앞
741880       세곡동사거리  장지교차로(동부간선도로)

[328641 rows x 2 columns]

In [16]:
car[car.cluster==1][col]

           start_point       end_point
18                 일원역             수서역
20                 수서역             일원역
80              세곡동사거리             수서역
83                 수서역          세곡동사거리
97              청담대교남단  탄천IC진출(동부간선도로)
99      탄천IC진입(동부간선도로)    수서IC(동부간선도로)
100       수서IC(동부간선도로)           복정교차로
101              복정교차로    수서IC(동부간선도로)
102       수서IC(동부간선도로)  탄천IC진입(동부간선도로)
103     탄천IC진입(동부간선도로)     동부간선올림픽대로진출
198               구룡터널            내곡IC
249             영동대교남단          성수대교남단
253             성수대교남단          영동대교남단
294             세곡동사거리            내곡IC
313                일원역             수서역
315                수서역             일원역
375             세곡동사거리             수서역
378                수서역          세곡동사거리
392             청담대교남단  탄천IC진출(동부간선도로)
394     탄천IC진입(동부간선도로)    수서IC(동부간선도로)
395       수서IC(동부간선도로)           복정교차로
396              복정교차로    수서IC(동부간선도로)
397       수서IC(동부간선도로)  탄천IC진입(동부간선도로)
398     탄천IC진입(동부간선도로)     동부간선올림픽대로진출
493               구룡터널            내곡IC
544             영동대교남단          성수대교남단
548             성수대교남단          영동대교남단
589             세곡동사거리            내곡IC
608                일원역             수서역
610                수서역             일원역
...                ...             ...
741255          성수대교남단          영동대교남단
741295          세곡동사거리            내곡IC
741314             일원역             수서역
741316             수서역             일원역
741376          세곡동사거리             수서역
741379             수서역          세곡동사거리
741393          청담대교남단  탄천IC진출(동부간선도로)
741395  탄천IC진입(동부간선도로)    수서IC(동부간선도로)
741396    수서IC(동부간선도로)           복정교차로
741397           복정교차로    수서IC(동부간선도로)
741398    수서IC(동부간선도로)  탄천IC진입(동부간선도로)
741399  탄천IC진입(동부간선도로)     동부간선올림픽대로진출
741493            구룡터널            내곡IC
741544          영동대교남단          성수대교남단
741548          성수대교남단          영동대교남단
741588          세곡동사거리            내곡IC
741607             일원역             수서역
741609             수서역             일원역
741669          세곡동사거리             수서역
741672             수서역          세곡동사거리
741686          청담대교남단  탄천IC진출(동부간선도로)
741688  탄천IC진입(동부간선도로)    수서IC(동부간선도로)
741689    수서IC(동부간선도로)           복정교차로
741690           복정교차로    수서IC(동부간선도로)
741691    수서IC(동부간선도로)  탄천IC진입(동부간선도로)
741692  탄천IC진입(동부간선도로)     동부간선올림픽대로진출
741786            구룡터널            내곡IC
741837          영동대교남단          성수대교남단
741841          성수대교남단          영동대교남단
741881          세곡동사거리            내곡IC

[34426 rows x 2 columns]

In [17]:
car[car.cluster==2][col]

         start_point      end_point
0              우성아파트            강남역
1              우성아파트          뱅뱅사거리
3                대청역          수서경찰서
4              수서경찰서         대모산입구역
5             대모산입구역       개포2동주민센터
6           개포2동주민센터           개포동역
8               개포고교           구룡초교
10              구룡초교           개포고교
12              개포동역       개포2동주민센터
13          개포2동주민센터         대모산입구역
14            대모산입구역          수서경찰서
15             수서경찰서            대청역
22               매봉역           매봉터널
23              매봉터널            도곡역
27            탄천1교서측    남부순환로탄천IC합류
32       남부순환로탄천IC합류         탄천1교서측
36               도곡역           매봉터널
37              매봉터널            매봉역
38               매봉역          양재전화국
44               역삼역         구역삼세무서
45            구역삼세무서       도곡1동주민센터
47            영동2교북단          포이사거리
48              구룡사앞          국악고교앞
49            영동2교북단        영동2교교차로
50          도곡1동주민센터         구역삼세무서
51            구역삼세무서            역삼역
58          싸리고개공원입구       도곡1동주민센터
59          도곡1동주민센터         영동세브란스
60            영동세브란스            한티역
66               한티역         영동세브란스
...              ...            ...
741829      대치동우성아파트           휘문고교
741830          휘문고교            삼성역
741833         경기고교앞      영동대교남단교차로
741834     영동대교남단교차로         영동대교남단
741843   올림픽대로동부간선JC           청담IC
741844           대청역           영희초교
741845          영희초교         삼성서울병원
741848        삼성서울병원           영희초교
741849          영희초교            대청역
741850        한남IC동측  한남IC서측(설악아파트)
741851         강남경찰서            삼성역
741854           선릉역         르네상스호텔
741855        르네상스호텔            역삼역
741856           역삼역           국기원앞
741857          국기원앞            강남역
741858          국기원앞            역삼역
741859           역삼역         르네상스호텔
741860        르네상스호텔            선릉역
741863           삼성역          강남경찰서
741864         강남경찰서         정신여중고앞
741865         강남경찰서        강남면허시험장
741866       강남면허시험장          강남경찰서
741867  올림픽대로동부간선분기점            봉은교
741868       강남면허시험장          삼성교서측
741869         삼성교서측            봉은교
741870           봉은교   올림픽대로동부간선분기점
741873         강남구청역           서울세관
741874          서울세관            학동역
741876           학동역           서울세관
741877          서울세관          강남구청역

[378815 rows x 2 columns]

In [21]:
print('cluster 0')
print(car[car.cluster==0]['road_type'].value_counts()/len(car[car.cluster==0]))

print('cluster 1')
print(car[car.cluster==1]['road_type'].value_counts()/len(car[car.cluster==1]))

print('cluster 2')
print(car[car.cluster==2]['road_type'].value_counts()/len(car[car.cluster==2]))

cluster 0
주간선도로     0.546274
보조간선도로    0.246250
기타도로      0.153907
도시고속도로    0.053569
Name: road_type, dtype: float64
cluster 1
도시고속도로    0.559228
주간선도로     0.440772
Name: road_type, dtype: float64
cluster 2
주간선도로     0.420332
보조간선도로    0.316078
기타도로      0.250312
도시고속도로    0.013278
Name: road_type, dtype: float64

In [24]:
car.road_type.value_counts() / len(car)

주간선도로     0.477070
보조간선도로    0.270478
기타도로      0.195991
도시고속도로    0.056460
Name: road_type, dtype: float64

In [25]:
car.road_num.value_counts() / len(car)

3.0    0.310040
4.0    0.303296
2.0    0.193833
5.0    0.095279
1.0    0.047687
7.0    0.030619
6.0    0.013636
0.0    0.005610
Name: road_num, dtype: float64

In [26]:
print('cluster 0')
print(car[car.cluster==0]['road_num'].value_counts()/len(car[car.cluster==0]))

print('cluster 1')
print(car[car.cluster==1]['road_num'].value_counts()/len(car[car.cluster==1]))

print('cluster 2')
print(car[car.cluster==2]['road_num'].value_counts()/len(car[car.cluster==2]))

cluster 0
4.0    0.330899
3.0    0.315423
2.0    0.146211
5.0    0.107564
7.0    0.046035
1.0    0.038477
6.0    0.015391
Name: road_num, dtype: float64
cluster 1
3.0    0.659531
5.0    0.146110
0.0    0.120897
2.0    0.073462
Name: road_num, dtype: float64
cluster 2
4.0    0.306912
3.0    0.273608
2.0    0.246086
5.0    0.080002
1.0    0.060011
7.0    0.020028
6.0    0.013352
Name: road_num, dtype: float64

In [27]:
car[car.road_num==7]['road_type'].value_counts()

주간선도로     20201
도시고속도로     2515
Name: road_type, dtype: int64